version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: productmanager
    environment:
      POSTGRES_DB: produtos_db
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - productmanager_network

volumes:
  postgres_data:

networks:
  productmanager_network:
    driver: bridge
