GET http://localhost:8080/api/produtos
Accept: application/json

###
GET http://localhost:8080/api/produtos/4
Accept: application/json

###
POST http://localhost:8080/api/produtos
Accept: application/json
Content-Type: application/json

{
    "nome": "Teclado Bluetooth",
    "descricao": "Acesso remoto ao computador",
    "responsavel": "Claudionei",
    "tipoCategoria": "Acessórios"
}

###
PUT http://localhost:8080/api/produtos/6
Accept: application/json
Content-Type: application/json

{
    "nome": "Teclado Wireless",
    "descricao": "Acesso remoto ao notebook",
    "responsavel": "Claudionei de Aguiar",
    "tipoCategoria": "Acessórios"
}

###
DELETE http://localhost:8080/api/produtos/6/hard